# Generated by Django 4.0.5 on 2022-06-08 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=50)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('mobile', phone_field.models.PhoneField(blank=True, help_text='Contact mobile number', max_length=31)),
                ('companyname', models.CharField(max_length=250)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now_add=True)),
                ('clientstatus', models.BooleanField(default=False, verbose_name='prospect/Client')),
                ('salescontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now_add=True)),
                ('eventstatus', models.BooleanField(default=False, verbose_name='en cours/Terminé')),
                ('attendees', models.IntegerField()),
                ('eventdate', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients')),
                ('supportcontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateupdated', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('paymentdue', models.DateTimeField(auto_now_add=True)),
                ('contractstatus', models.BooleanField(default=False, verbose_name='contrat non signé/Signé')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients')),
                ('salescontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
