# Generated by Django 4.0.5 on 2022-06-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_contrats_client_alter_events_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrats',
            old_name='contractstatus',
            new_name='contratstatus',
        ),
        migrations.RemoveField(
            model_name='contrats',
            name='status',
        ),
    ]
