# Generated by Django 4.0.5 on 2022-06-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_rename_contractstatus_contrats_contratstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='contrat',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='crm.contrats'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clients'),
        ),
    ]
