# Generated by Django 4.0.5 on 2022-07-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_events_contrat_alter_events_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contrats',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='crm.clients'),
        ),
        migrations.AlterField(
            model_name='events',
            name='dateupdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='eventdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
