# Generated by Django 4.0.5 on 2022-06-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gestion', 'Gestion'), ('vente', 'Vente'), ('support', 'Support')], max_length=20),
        ),
    ]
